# server
host = "localhost"
port = 3001

# CORS
access_control_allow_origin = "*"
access_control_allow_headers = "Origin, Accept, Content-Type, Content-Length, Accept-Encoding"
access_control_allow_methods = "*"

# sqllite
abs_path_to_database = "database/sqlite.db"